server:
  port:
    5002

spring:
  application:
    name: STAFF-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://root:hafiz@cluster0.kc42y.mongodb.net/takeaway


eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
