server:
  port: 5000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STAFF-SERVICE
          uri: lb://STAFF-SERVICE
          predicates:
            - Path=/staff/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost